# Generated by Django 4.2.7 on 2026-04-11 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0002_branch"),
        ("accounts", "0006_globalconfiguration_trial_period_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmJoinLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("platform_owner", "Platform Owner"),
                            ("partner_manager", "Partner Manager"),
                            ("super_admin", "Super Admin (Firm Owner)"),
                            ("admin", "Admin"),
                            ("advocate", "Advocate"),
                            ("paralegal", "Paralegal"),
                            ("client", "Client"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_uses",
                    models.IntegerField(default=0, help_text="0 for unlimited"),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_links",
                        to="firms.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["firm", "user_type", "is_active"],
                        name="accounts_fi_firm_id_b4122c_idx",
                    )
                ],
            },
        ),
    ]
