# Generated by Django 5.2.13 on 2026-04-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="case_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed fee per case",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="consultation_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="One-time consultation fee",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="fee_currency",
            field=models.CharField(
                default="INR", help_text="Currency code (e.g., INR, USD)", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hourly rate for advocate services",
                max_digits=10,
                null=True,
            ),
        ),
    ]
