# Generated by Django 4.2.7 on 2026-04-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0008_alter_case_additional_expenses_and_more"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="cases.case",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="cases.case",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="cases.case",
            ),
        ),
    ]
