# Generated by Django 4.2.7 on 2026-04-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("billing", "0002_alter_expense_case_alter_invoice_case_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="firms.branch",
            ),
        ),
    ]
