# Generated by Django 4.2.7 on 2026-04-27 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("billing", "0003_invoice_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvocateInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "period_start",
                    models.DateField(help_text="Start date of billing period"),
                ),
                (
                    "period_end",
                    models.DateField(help_text="End date of billing period"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total from time entries",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax percentage if applicable",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount to be paid",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advocate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advocate_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_advocate_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advocate_invoices",
                        to="firms.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="timeentry",
            name="advocate_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="billing.advocateinvoice",
            ),
        ),
        migrations.AddIndex(
            model_name="advocateinvoice",
            index=models.Index(
                fields=["firm", "advocate", "status"],
                name="billing_adv_firm_id_8ed630_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="advocateinvoice",
            index=models.Index(
                fields=["invoice_number"], name="billing_adv_invoice_156c4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advocateinvoice",
            index=models.Index(
                fields=["invoice_date"], name="billing_adv_invoice_083b77_idx"
            ),
        ),
    ]
