# Generated by Django 4.2.7 on 2026-04-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_advocateinvoice_timeentry_advocate_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="balance_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
