# Generated by Django 4.2.7 on 2026-04-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_subscriptionplan_enable_api_access_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_admins",
            field=models.IntegerField(
                default=5, help_text="Maximum number of admins allowed"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_advocates",
            field=models.IntegerField(
                default=10, help_text="Maximum number of advocates allowed"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_branches",
            field=models.IntegerField(
                default=5, help_text="Maximum number of branches"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_cases",
            field=models.IntegerField(
                default=500, help_text="Maximum number of active cases allowed"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_clients",
            field=models.IntegerField(
                default=500, help_text="Maximum number of clients"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_paralegals",
            field=models.IntegerField(
                default=10, help_text="Maximum number of paralegals allowed"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_storage_gb",
            field=models.IntegerField(default=50, help_text="Storage limit in GB"),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_users",
            field=models.IntegerField(
                default=30, help_text="Maximum total team members"
            ),
        ),
    ]
