# Generated by Django 4.2.7 on 2026-04-27 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("subscriptions", "0003_increase_subscription_limits"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField()),
                (
                    "period_start",
                    models.DateField(help_text="Start date of billing period"),
                ),
                (
                    "period_end",
                    models.DateField(help_text="End date of billing period"),
                ),
                (
                    "plan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Subscription plan amount",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        help_text="Tax percentage (e.g., GST 18%)",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount including tax",
                        max_digits=10,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining balance to be paid",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("upi", "UPI"),
                            ("card", "Credit/Debit Card"),
                            ("cheque", "Cheque"),
                            ("online", "Online Payment"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("payment_notes", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes visible to firm"),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes not visible to firm"
                    ),
                ),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_platform_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_invoices",
                        to="firms.firm",
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_invoices",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["firm", "status"], name="subscriptio_firm_id_2b6573_idx"
                    ),
                    models.Index(
                        fields=["invoice_number"], name="subscriptio_invoice_bca470_idx"
                    ),
                    models.Index(
                        fields=["invoice_date"], name="subscriptio_invoice_cebd76_idx"
                    ),
                ],
            },
        ),
    ]
