# Generated by Django 4.2.7 on 2026-05-04 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_solo_advocate_support"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="solo_advocate",
        ),
    ]
