# Generated by Django 4.2.7 on 2026-06-01 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_add_logo_registration_practice_areas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0005_client_firm_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="user_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("user_account", "firm")},
        ),
    ]
