# Generated by Django 4.2.7 on 2026-04-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_documents",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="document_category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="userdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("aadhar", "Aadhar Card"),
                    ("pan", "PAN Card"),
                    ("passport", "Passport"),
                    ("driving_license", "Driving License"),
                    ("bar_certificate", "Bar Council Certificate"),
                    ("degree", "Educational Degree"),
                    ("fir", "FIR"),
                    ("petition", "Petition"),
                    ("evidence", "Evidence"),
                    ("order", "Court Order"),
                    ("agreement", "Agreement"),
                    ("affidavit", "Affidavit"),
                    ("notice", "Legal Notice"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
