# Generated by Django 4.2.7 on 2026-05-20 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0014_update_legal_notice_tracking"),
        ("clients", "0005_client_firm_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0005_alter_userdocument_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourtFormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Form No 45 Bail Bond", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bail_bond", "Bail Bond"),
                            ("vakalatnama", "Vakalatnama"),
                            ("memo_appearance", "Memorandum of Appearance"),
                            ("affidavit", "Affidavit"),
                            ("petition", "Petition"),
                            ("application", "Application"),
                            ("notice", "Notice"),
                            ("undertaking", "Undertaking"),
                            ("surety_bond", "Surety Bond"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content_structure",
                    models.JSONField(
                        default=dict,
                        help_text='\n        JSON structure defining the document layout:\n        {\n            "page_size": "A4",\n            "margins": {"top": 72, "right": 72, "bottom": 72, "left": 72},\n            "sections": [\n                {\n                    "type": "header",\n                    "content": "IN THE COURT OF...",\n                    "style": {"align": "center", "bold": true, "size": 14}\n                },\n                {\n                    "type": "paragraph",\n                    "content": "This is to certify that...",\n                    "fields": [\n                        {"name": "party_name", "placeholder": "[Party Name]", "position": 25}\n                    ]\n                },\n                {\n                    "type": "table",\n                    "columns": ["Sr. No.", "Description", "Amount"],\n                    "rows": 3,\n                    "dynamic": true\n                }\n            ]\n        }\n        ',
                    ),
                ),
                (
                    "default_field_mappings",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Maps template fields to case/client data:\n        {\n            "court_name": "case.court_name",\n            "party_name": "client.full_name",\n            "case_number": "case.case_number"\n        }\n        ',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Court Form Template",
                "verbose_name_plural": "Court Form Templates",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="FilledCourtForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "filled_content",
                    models.JSONField(
                        default=dict, help_text="Complete document with filled values"
                    ),
                ),
                (
                    "field_values",
                    models.JSONField(
                        default=dict, help_text="Key-value pairs of filled fields"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("reviewed", "Reviewed"),
                            ("signed", "Signed"),
                            ("filed", "Filed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("advocate_signed", models.BooleanField(default=False)),
                (
                    "advocate_signature_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("client_signed", models.BooleanField(default=False)),
                ("client_signature_date", models.DateTimeField(blank=True, null=True)),
                ("is_shared_with_client", models.BooleanField(default=False)),
                ("shared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF file",
                        null=True,
                        upload_to="court_forms/generated/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Filled Court Form",
                "verbose_name_plural": "Filled Court Forms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="filledtemplate",
            name="documents_f_client__07a01b_idx",
        ),
        migrations.RemoveIndex(
            model_name="filledtemplate",
            name="documents_f_firm_id_1327d6_idx",
        ),
        migrations.AlterField(
            model_name="filledtemplate",
            name="filled_data",
            field=models.JSONField(
                default=dict, help_text="Key-value pairs of filled fields"
            ),
        ),
        migrations.AlterField(
            model_name="filledtemplate",
            name="generated_file",
            field=models.FileField(
                blank=True,
                help_text="Generated document file",
                null=True,
                upload_to="filled_templates/",
            ),
        ),
        migrations.AlterField(
            model_name="filledtemplate",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="filledtemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("completed", "Completed"),
                    ("shared", "Shared with Client"),
                    ("signed", "Signed"),
                    ("filed", "Filed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="filledtemplate",
            index=models.Index(
                fields=["client", "status"], name="documents_f_client__00ebcc_idx"
            ),
        ),
        migrations.AddField(
            model_name="filledcourtform",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="court_forms",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="filledcourtform",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="court_forms",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="filledcourtform",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_court_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filledcourtform",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="filled_forms",
                to="documents.courtformtemplate",
            ),
        ),
        migrations.AddField(
            model_name="courtformtemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_form_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
