# Generated by Django 4.2.7 on 2026-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_filledcourtform_advocate_signature_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filledcourtform",
            name="digital_signature_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Metadata about the USB token signature (serial, issuer, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="filledcourtform",
            name="is_digitally_signed",
            field=models.BooleanField(default=False),
        ),
    ]
