# Generated by Django 4.2.7 on 2026-05-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_filledcourtform_digital_signature_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filledtemplate",
            name="advocate_signature_image",
            field=models.ImageField(
                blank=True,
                help_text="Advocate's signature image",
                null=True,
                upload_to="signatures/advocate/",
            ),
        ),
        migrations.AddField(
            model_name="filledtemplate",
            name="client_signature_image",
            field=models.ImageField(
                blank=True,
                help_text="Client's signature image",
                null=True,
                upload_to="signatures/client/",
            ),
        ),
    ]
