# Generated by Django 4.2.7 on 2026-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_filledtemplate_advocate_signature_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courtformtemplate",
            options={
                "ordering": ["sequence", "category", "name"],
                "verbose_name": "Court Form Template",
                "verbose_name_plural": "Court Form Templates",
            },
        ),
        migrations.AddField(
            model_name="courtformtemplate",
            name="sequence",
            field=models.IntegerField(
                default=0, help_text="Ordering sequence for templates"
            ),
        ),
    ]
