# Generated by Django 4.2.7 on 2026-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_alter_courtformtemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtformtemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("bail_bond", "Bail Bond"),
                    ("vakalatnama", "Vakalatnama"),
                    ("memo_appearance", "Memorandum of Appearance"),
                    ("affidavit", "Affidavit"),
                    ("petition", "Petition"),
                    ("application", "Application"),
                    ("notice", "Notice"),
                    ("undertaking", "Undertaking"),
                    ("surety_bond", "Surety Bond"),
                    ("drafting", "Drafting Workspace"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
