# Generated by Django 4.2.7 on 2026-05-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_alter_courtformtemplate_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="filledcourtform",
            name="custom_sequence",
            field=models.IntegerField(
                default=0, help_text="Manual override for document ordering"
            ),
        ),
    ]
