# Generated by Django 4.2.11 on 2026-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_userdocument_is_in_all_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='is_copied',
            field=models.BooleanField(default=False, help_text='Flag indicating if this document was created via Copy'),
        ),
    ]
