# Generated by Django 4.2.11 on 2026-08-18 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_update_legal_notice_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0014_userdocument_is_copied'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDraftVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('version_name', models.CharField(default='Auto-saved Draft', max_length=255)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('annotation_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('snapshot_data', models.JSONField(blank=True, default=dict, help_text='Serialized JSON of mobile-store workspace state (highlights, ink, notes, bookmarks)')),
                ('pdf_file', models.FileField(blank=True, help_text='Optional PDF snapshot binary', null=True, upload_to='draft_versions/%Y/%m/%d/')),
                ('is_named', models.BooleanField(default=False, help_text='True if manually named by the advocate as a key milestone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(help_text='Case this draft version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='draft_versions', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_draft_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, help_text='Master document or file this snapshot was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_versions', to='documents.userdocument')),
            ],
            options={
                'verbose_name': 'Case Draft Version',
                'verbose_name_plural': 'Case Draft Versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
