# Generated by Django 4.2.11 on 2026-08-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_casedraftversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedraftversion',
            name='document_identifier',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique identifier of the specific file or court form (e.g. doc-master-xxx, doc-case-xxx, doc-form-xxx)', max_length=255),
        ),
    ]
