# Generated by Django 4.2.11 on 2026-08-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_casedraftversion_document_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdocument',
            options={'ordering': ['custom_sequence', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='userdocument',
            name='custom_sequence',
            field=models.IntegerField(default=0, help_text='Manual override for filing pack document ordering'),
        ),
    ]
