# Generated by Django 4.2.11 on 2026-09-07 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_update_legal_notice_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0017_alter_userdocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name / Title of this signature (e.g. 'Advocate Primary', 'Client - Rahul', 'Official Notary Stamp')", max_length=255)),
                ('signature_type', models.CharField(choices=[('advocate', 'Advocate Signature'), ('client', 'Client / Deponent Signature'), ('witness', 'Witness Signature'), ('co_counsel', 'Co-Counsel Signature'), ('notary_seal', 'Notary / Seal Stamp'), ('custom', 'Custom Signature / Stamp')], default='advocate', max_length=50)),
                ('image', models.ImageField(help_text='Signature / Stamp image file uploaded to CDN / backend storage', upload_to='signatures/cases/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_signatures', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_case_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Signature',
                'verbose_name_plural': 'Case Signatures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='documents_c_case_id_855380_idx')],
            },
        ),
    ]
