# Generated by Django 4.2.7 on 2026-04-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("cases", "0001_initial"),
        ("firms", "0002_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="firm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="firms.firm",
            ),
        ),
    ]
