# Generated by Django 4.2.7 on 2026-05-11 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0010_casedocumentrequest"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="casedocumentrequest",
            new_name="cases_cased_case_id_e562fe_idx",
            old_name="cases_cased_case_id_b8c9e5_idx",
        ),
        migrations.RenameIndex(
            model_name="casedocumentrequest",
            new_name="cases_cased_status_91adee_idx",
            old_name="cases_cased_status_f3a2d1_idx",
        ),
    ]
