# Generated by Django 4.2.7 on 2026-05-13 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "cases",
            "0011_rename_cases_cased_case_id_b8c9e5_idx_cases_cased_case_id_e562fe_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("summons", "Summons"),
                            ("notice", "Notice"),
                            ("order", "Order"),
                            ("warrant", "Warrant"),
                        ],
                        default="summons",
                        max_length=20,
                    ),
                ),
                (
                    "service_date",
                    models.DateField(help_text="Date when service was attempted"),
                ),
                (
                    "service_method",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Service"),
                            ("registered_post", "Registered Post"),
                            ("courier", "Courier"),
                            ("publication", "Publication in Newspaper"),
                            ("email", "Email"),
                            ("affixture", "Affixture on Property"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "served_to",
                    models.CharField(
                        blank=True,
                        help_text="Name of person who received",
                        max_length=255,
                    ),
                ),
                (
                    "served_by",
                    models.CharField(
                        blank=True, help_text="Process server name", max_length=255
                    ),
                ),
                (
                    "address",
                    models.TextField(help_text="Address where service was attempted"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("served", "Served Successfully"),
                            ("unserved", "Unserved"),
                            ("returned", "Returned Unserved"),
                            ("refused", "Refused by Recipient"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload proof of service (acknowledgment, postal receipt, etc.)",
                        null=True,
                        upload_to="service_proofs/",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Any notes or observations"),
                ),
                (
                    "next_attempt_date",
                    models.DateField(
                        blank=True,
                        help_text="If failed, when to attempt next",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_attempts",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_attempts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Attempt",
                "verbose_name_plural": "Service Attempts",
                "ordering": ["-service_date"],
            },
        ),
    ]
