# Generated by Django 4.2.7 on 2026-05-13 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0004_documenttemplate_filledtemplate_and_more"),
        ("cases", "0012_serviceattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("civil", "Civil Case"),
                            ("criminal", "Criminal Case"),
                            ("family", "Family Law"),
                            ("property", "Property Dispute"),
                            ("consumer", "Consumer Case"),
                            ("labour", "Labour Dispute"),
                            ("corporate", "Corporate/Commercial"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Name of required document", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this document is for"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True, help_text="Is this document required?"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order to display in checklist"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document Checklist Template",
                "verbose_name_plural": "Document Checklist Templates",
                "ordering": ["case_type", "display_order", "document_name"],
            },
        ),
        migrations.CreateModel(
            name="LegalNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("legal_notice", "Legal Notice"),
                            ("demand_notice", "Demand Notice"),
                            ("termination_notice", "Termination Notice"),
                            ("eviction_notice", "Eviction Notice"),
                            ("cease_desist", "Cease and Desist"),
                            ("other", "Other"),
                        ],
                        default="legal_notice",
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_address", models.TextField()),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                ("notice_content", models.TextField(help_text="Full notice text")),
                (
                    "notice_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload final notice PDF",
                        null=True,
                        upload_to="legal_notices/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready_to_send", "Ready to Send"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("response_received", "Response Received"),
                            ("no_response", "No Response"),
                            ("deadline_expired", "Deadline Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("registered_post", "Registered Post"),
                            ("speed_post", "Speed Post"),
                            ("courier", "Courier"),
                            ("email", "Email"),
                            ("hand_delivery", "Hand Delivery"),
                            ("publication", "Publication in Newspaper"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sent_date", models.DateField(blank=True, null=True)),
                ("delivered_date", models.DateField(blank=True, null=True)),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        help_text="Post/courier tracking number",
                        max_length=100,
                    ),
                ),
                (
                    "proof_of_delivery",
                    models.FileField(
                        blank=True,
                        help_text="Upload delivery receipt/acknowledgment",
                        null=True,
                        upload_to="notice_proofs/",
                    ),
                ),
                (
                    "response_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Deadline for response (usually 15-30 days)",
                        null=True,
                    ),
                ),
                ("response_received_date", models.DateField(blank=True, null=True)),
                (
                    "response_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload response from other party",
                        null=True,
                        upload_to="notice_responses/",
                    ),
                ),
                (
                    "response_summary",
                    models.TextField(blank=True, help_text="Summary of their response"),
                ),
                (
                    "next_action",
                    models.TextField(
                        blank=True, help_text="What to do next based on response"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_notices",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_notices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Notice",
                "verbose_name_plural": "Legal Notices",
                "ordering": ["-sent_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseResearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "research_type",
                    models.CharField(
                        choices=[
                            ("legal_research", "Legal Research"),
                            ("case_law", "Case Law / Precedent"),
                            ("statute", "Statute / Act Reference"),
                            ("strategy", "Case Strategy"),
                            ("facts_analysis", "Facts Analysis"),
                            ("other", "Other"),
                        ],
                        default="legal_research",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(help_text="Research notes, analysis, strategy"),
                ),
                (
                    "case_citation",
                    models.CharField(
                        blank=True, help_text="e.g., AIR 2020 SC 1234", max_length=500
                    ),
                ),
                ("court_name", models.CharField(blank=True, max_length=255)),
                ("judgment_date", models.DateField(blank=True, null=True)),
                (
                    "act_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Indian Penal Code, 1860",
                        max_length=255,
                    ),
                ),
                (
                    "section_number",
                    models.CharField(
                        blank=True, help_text="e.g., Section 420", max_length=100
                    ),
                ),
                (
                    "reference_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload judgment copy, article, etc.",
                        null=True,
                        upload_to="case_research/",
                    ),
                ),
                (
                    "is_favorable",
                    models.BooleanField(
                        default=True,
                        help_text="Is this precedent favorable to our case?",
                    ),
                ),
                (
                    "relevance_score",
                    models.IntegerField(
                        default=5, help_text="How relevant is this? (1-10)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_notes",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_notes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Research Note",
                "verbose_name_plural": "Case Research Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseDocumentChecklistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("requested", "Requested from Client"),
                            ("received", "Received"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected - Need Reupload"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_date", models.DateField(blank=True, null=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("verified_date", models.DateField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Verification notes or rejection reason"
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("last_reminder_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_checklist_items",
                        to="cases.case",
                    ),
                ),
                (
                    "checklist_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to template if created from template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.documentchecklist",
                    ),
                ),
                (
                    "uploaded_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_items",
                        to="documents.userdocument",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_documents_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Document Checklist Item",
                "verbose_name_plural": "Case Document Checklist Items",
                "ordering": ["case", "is_mandatory", "document_name"],
            },
        ),
    ]
