# Generated by Django 4.2.7 on 2026-05-15 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0013_documentchecklist_legalnotice_caseresearch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalnotice",
            name="delivery_attempts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Track multiple delivery attempts with different methods",
            ),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="email_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="email_opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="email_opened_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="email_sent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="last_status_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="last_status_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notice_status_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="physical_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="physical_delivered_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="physical_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="physical_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="read_date",
            field=models.DateField(
                blank=True, help_text="When recipient read the notice", null=True
            ),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="status_notes",
            field=models.TextField(blank=True, help_text="Notes about status changes"),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="whatsapp_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="whatsapp_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="whatsapp_read_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="whatsapp_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="legalnotice",
            name="whatsapp_sent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="legalnotice",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registered_post", "Registered Post"),
                    ("speed_post", "Speed Post"),
                    ("courier", "Courier"),
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("hand_delivery", "Hand Delivery"),
                    ("publication", "Publication in Newspaper"),
                    ("multiple", "Multiple Methods"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="legalnotice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready_to_send", "Ready to Send"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read by Recipient"),
                    ("response_received", "Response Received"),
                    ("no_response", "No Response"),
                    ("deadline_expired", "Deadline Expired"),
                    ("bounced", "Delivery Failed/Bounced"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
